export const ONLYOFFICE_VOLTO_CONFIG_GET = 'ONLYOFFICE_VOLTO_CONFIG_GET';
export const ONLYOFFICE_VOLTO_SETTINGS_SAVE = 'ONLYOFFICE_VOLTO_SETTINGS_SAVE';
export const ONLYOFFICE_VOLTO_SETTINGS_FORMS =
  'ONLYOFFICE_VOLTO_SETTINGS_FORMS';
